// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGuqzAO2vuV8724YYo2JrdvC4rNSeK068',
    appId: '1:203635799704:web:30d1f665e49f4dc924c2ed',
    messagingSenderId: '203635799704',
    projectId: 'fir-tutorial-b34e7',
    authDomain: 'fir-tutorial-b34e7.firebaseapp.com',
    storageBucket: 'fir-tutorial-b34e7.appspot.com',
    measurementId: 'G-BYMC48S4FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu7tfL4bb_rwJU_Byk3CkweePKEnVUwzc',
    appId: '1:203635799704:android:1b571bb960ab7b2c24c2ed',
    messagingSenderId: '203635799704',
    projectId: 'fir-tutorial-b34e7',
    storageBucket: 'fir-tutorial-b34e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjxcwz2IFjx-EmNrSpfYEq_Ob1VM2Kpt4',
    appId: '1:203635799704:ios:ff99ceed612ffc3d24c2ed',
    messagingSenderId: '203635799704',
    projectId: 'fir-tutorial-b34e7',
    storageBucket: 'fir-tutorial-b34e7.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjxcwz2IFjx-EmNrSpfYEq_Ob1VM2Kpt4',
    appId: '1:203635799704:ios:ff99ceed612ffc3d24c2ed',
    messagingSenderId: '203635799704',
    projectId: 'fir-tutorial-b34e7',
    storageBucket: 'fir-tutorial-b34e7.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGuqzAO2vuV8724YYo2JrdvC4rNSeK068',
    appId: '1:203635799704:web:603f9761b812e38224c2ed',
    messagingSenderId: '203635799704',
    projectId: 'fir-tutorial-b34e7',
    authDomain: 'fir-tutorial-b34e7.firebaseapp.com',
    storageBucket: 'fir-tutorial-b34e7.appspot.com',
    measurementId: 'G-M9G1CTD6HE',
  );
}
